// Auto-generated. Do not edit!

// (in-package optoforce_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class OptoForceGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.store = null;
      this.acq_duration = null;
      this.publish_freq = null;
    }
    else {
      if (initObj.hasOwnProperty('store')) {
        this.store = initObj.store
      }
      else {
        this.store = false;
      }
      if (initObj.hasOwnProperty('acq_duration')) {
        this.acq_duration = initObj.acq_duration
      }
      else {
        this.acq_duration = 0.0;
      }
      if (initObj.hasOwnProperty('publish_freq')) {
        this.publish_freq = initObj.publish_freq
      }
      else {
        this.publish_freq = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type OptoForceGoal
    // Serialize message field [store]
    bufferOffset = _serializer.bool(obj.store, buffer, bufferOffset);
    // Serialize message field [acq_duration]
    bufferOffset = _serializer.float64(obj.acq_duration, buffer, bufferOffset);
    // Serialize message field [publish_freq]
    bufferOffset = _serializer.int32(obj.publish_freq, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type OptoForceGoal
    let len;
    let data = new OptoForceGoal(null);
    // Deserialize message field [store]
    data.store = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [acq_duration]
    data.acq_duration = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [publish_freq]
    data.publish_freq = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 13;
  }

  static datatype() {
    // Returns string type for a message object
    return 'optoforce_ros/OptoForceGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '69e819ebc559709f7bffac7bbf22dba5';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    bool store
    float64 acq_duration
    int32 publish_freq
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new OptoForceGoal(null);
    if (msg.store !== undefined) {
      resolved.store = msg.store;
    }
    else {
      resolved.store = false
    }

    if (msg.acq_duration !== undefined) {
      resolved.acq_duration = msg.acq_duration;
    }
    else {
      resolved.acq_duration = 0.0
    }

    if (msg.publish_freq !== undefined) {
      resolved.publish_freq = msg.publish_freq;
    }
    else {
      resolved.publish_freq = 0
    }

    return resolved;
    }
};

module.exports = OptoForceGoal;
