// Auto-generated. Do not edit!

// (in-package optoforce_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class OptoForceFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.wrench_lst = null;
    }
    else {
      if (initObj.hasOwnProperty('wrench_lst')) {
        this.wrench_lst = initObj.wrench_lst
      }
      else {
        this.wrench_lst = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type OptoForceFeedback
    // Serialize message field [wrench_lst]
    // Serialize the length for message field [wrench_lst]
    bufferOffset = _serializer.uint32(obj.wrench_lst.length, buffer, bufferOffset);
    obj.wrench_lst.forEach((val) => {
      bufferOffset = geometry_msgs.msg.WrenchStamped.serialize(val, buffer, bufferOffset);
    });
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type OptoForceFeedback
    let len;
    let data = new OptoForceFeedback(null);
    // Deserialize message field [wrench_lst]
    // Deserialize array length for message field [wrench_lst]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.wrench_lst = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.wrench_lst[i] = geometry_msgs.msg.WrenchStamped.deserialize(buffer, bufferOffset)
    }
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    object.wrench_lst.forEach((val) => {
      length += geometry_msgs.msg.WrenchStamped.getMessageSize(val);
    });
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'optoforce_ros/OptoForceFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '33beeb9f57ea2f43c06c3f58af305729';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    geometry_msgs/WrenchStamped[] wrench_lst
    
    
    ================================================================================
    MSG: geometry_msgs/WrenchStamped
    # A wrench with reference coordinate frame and timestamp
    Header header
    Wrench wrench
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Wrench
    # This represents force in free space, separated into
    # its linear and angular parts.
    Vector3  force
    Vector3  torque
    
    ================================================================================
    MSG: geometry_msgs/Vector3
    # This represents a vector in free space. 
    # It is only meant to represent a direction. Therefore, it does not
    # make sense to apply a translation to it (e.g., when applying a 
    # generic rigid transformation to a Vector3, tf2 will only apply the
    # rotation). If you want your data to be translatable too, use the
    # geometry_msgs/Point message instead.
    
    float64 x
    float64 y
    float64 z
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new OptoForceFeedback(null);
    if (msg.wrench_lst !== undefined) {
      resolved.wrench_lst = new Array(msg.wrench_lst.length);
      for (let i = 0; i < resolved.wrench_lst.length; ++i) {
        resolved.wrench_lst[i] = geometry_msgs.msg.WrenchStamped.Resolve(msg.wrench_lst[i]);
      }
    }
    else {
      resolved.wrench_lst = []
    }

    return resolved;
    }
};

module.exports = OptoForceFeedback;
