controller_list:
  - name: fake_tx90_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses.
  - group: tx90_arm
    pose: home