(cl:defpackage optoforce_ros-msg
  (:use )
  (:export
   "<OPTOFORCEACTION>"
   "OPTOFORCEACTION"
   "<OPTOFORCEACTIONFEEDBACK>"
   "OPTOFORCEACTIONFEEDBACK"
   "<OPTOFORCEACTIONGOAL>"
   "OPTOFORCEACTIONGOAL"
   "<OPTOFORCEACTIONRESULT>"
   "OPTOFORCEACTIONRESULT"
   "<OPTOFORCEFEEDBACK>"
   "OPTOFORCEFEEDBACK"
   "<OPTOFORCEGOAL>"
   "OPTOFORCEGOAL"
   "<OPTOFORCERESULT>"
   "OPTOFORCERESULT"
  ))

