// Generated by gencpp from file staubli_tx90_planning/Coordinate_force.msg
// DO NOT EDIT!


#ifndef STAUBLI_TX90_PLANNING_MESSAGE_COORDINATE_FORCE_H
#define STAUBLI_TX90_PLANNING_MESSAGE_COORDINATE_FORCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Wrench.h>

namespace staubli_tx90_planning
{
template <class ContainerAllocator>
struct Coordinate_force_
{
  typedef Coordinate_force_<ContainerAllocator> Type;

  Coordinate_force_()
    : header()
    , point()
    , wrench()  {
    }
  Coordinate_force_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , point(_alloc)
    , wrench(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef  ::geometry_msgs::Wrench_<ContainerAllocator>  _wrench_type;
  _wrench_type wrench;





  typedef boost::shared_ptr< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> const> ConstPtr;

}; // struct Coordinate_force_

typedef ::staubli_tx90_planning::Coordinate_force_<std::allocator<void> > Coordinate_force;

typedef boost::shared_ptr< ::staubli_tx90_planning::Coordinate_force > Coordinate_forcePtr;
typedef boost::shared_ptr< ::staubli_tx90_planning::Coordinate_force const> Coordinate_forceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator1> & lhs, const ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.point == rhs.point &&
    lhs.wrench == rhs.wrench;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator1> & lhs, const ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace staubli_tx90_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e225759865dd432aff4d4f1ea18a73b";
  }

  static const char* value(const ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e225759865dd432ULL;
  static const uint64_t static_value2 = 0xaff4d4f1ea18a73bULL;
};

template<class ContainerAllocator>
struct DataType< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "staubli_tx90_planning/Coordinate_force";
  }

  static const char* value(const ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point point\n"
"geometry_msgs/Wrench wrench\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Wrench\n"
"# This represents force in free space, separated into\n"
"# its linear and angular parts.\n"
"Vector3  force\n"
"Vector3  torque\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.point);
      stream.next(m.wrench);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Coordinate_force_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::staubli_tx90_planning::Coordinate_force_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "wrench: ";
    s << std::endl;
    Printer< ::geometry_msgs::Wrench_<ContainerAllocator> >::stream(s, indent + "  ", v.wrench);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STAUBLI_TX90_PLANNING_MESSAGE_COORDINATE_FORCE_H
